spring.application.name=iot-temperature-monitor
spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
spring.datasource.username=your_username
spring.datasource.password=your_password

app.mail.alerts.enabled=true

spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=your_email_username
spring.mail.password=your_email_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true