CREATE TABLE password_reset_challenges
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    code_hash           VARCHAR(255)                            NOT NULL,
    issued_at           TIMESTAMPTZ                             NOT NULL,
    expires_at          TIMESTAMPTZ                             NOT NULL,
    resend_available_at TIMESTAMPTZ                             NOT NULL,
    failed_attempts     INTEGER                                 NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ                             NOT NULL,
    updated_at          TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_password_reset_challenges PRIMARY KEY (id),

    CONSTRAINT fk_password_reset_challenges_user
        FOREIGN KEY (user_id)
            REFERENCES app_users (id)
            ON DELETE CASCADE,

    CONSTRAINT ck_password_reset_challenges_code_hash_not_blank
        CHECK (btrim(code_hash) <> ''),

    CONSTRAINT ck_password_reset_challenges_failed_attempts
        CHECK (failed_attempts >= 0),

    CONSTRAINT ck_password_reset_challenges_issued_at
        CHECK (issued_at >= created_at),

    CONSTRAINT ck_password_reset_challenges_expires_at
        CHECK (expires_at > issued_at),

    CONSTRAINT ck_password_reset_challenges_resend_window
        CHECK (
            resend_available_at >= issued_at
                AND resend_available_at < expires_at
            ),

    CONSTRAINT ck_password_reset_challenges_updated_at
        CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uk_password_reset_challenges_user_id
    ON password_reset_challenges (user_id);

CREATE INDEX ix_password_reset_challenges_expires_at
    ON password_reset_challenges (expires_at);