CREATE TABLE hourly_sensor_summaries
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id             BIGINT                                  NOT NULL,
    bucket_start          TIMESTAMPTZ                             NOT NULL,
    bucket_end            TIMESTAMPTZ                             NOT NULL,
    source_sample_count   BIGINT                                  NOT NULL,
    unit                  VARCHAR(20),
    numeric_sum           NUMERIC,
    numeric_minimum       DOUBLE PRECISION,
    numeric_maximum       DOUBLE PRECISION,
    true_sample_count     BIGINT,
    finalized_at          TIMESTAMPTZ                             NOT NULL,
    refreshed_at          TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_hourly_sensor_summaries PRIMARY KEY (id),
    CONSTRAINT fk_hourly_sensor_summaries_sensor
        FOREIGN KEY (sensor_id)
            REFERENCES sensors (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_hourly_sensor_summaries_sensor_bucket_start
        UNIQUE (sensor_id, bucket_start),
    CONSTRAINT ck_hourly_sensor_summaries_bucket CHECK (
        bucket_end = bucket_start + INTERVAL '1 hour'
            AND bucket_start = (
            date_trunc('hour', bucket_start AT TIME ZONE 'UTC')
                AT TIME ZONE 'UTC'
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_sample_count
        CHECK (source_sample_count >= 0),
    CONSTRAINT ck_hourly_sensor_summaries_unit CHECK (
        unit IS NULL
            OR unit IN ('C', 'PERCENT')
        ),
    CONSTRAINT ck_hourly_sensor_summaries_value_shape CHECK (
        (
            unit IS NOT NULL
                AND true_sample_count IS NULL
                AND (
                (
                    source_sample_count = 0
                        AND numeric_sum IS NULL
                        AND numeric_minimum IS NULL
                        AND numeric_maximum IS NULL
                    )
                    OR
                (
                    source_sample_count > 0
                        AND numeric_sum IS NOT NULL
                        AND numeric_minimum IS NOT NULL
                        AND numeric_maximum IS NOT NULL
                    )
                )
            )
            OR
        (
            unit IS NULL
                AND numeric_sum IS NULL
                AND numeric_minimum IS NULL
                AND numeric_maximum IS NULL
                AND true_sample_count IS NOT NULL
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_true_sample_count CHECK (
        true_sample_count IS NULL
            OR true_sample_count BETWEEN 0 AND source_sample_count
        ),
    CONSTRAINT ck_hourly_sensor_summaries_numeric_sum_finite CHECK (
        numeric_sum IS NULL
            OR numeric_sum NOT IN (
                                   'NaN'::NUMERIC,
                                   'Infinity'::NUMERIC,
                                   '-Infinity'::NUMERIC
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_numeric_minimum_finite CHECK (
        numeric_minimum IS NULL
            OR numeric_minimum NOT IN (
                                       'NaN'::DOUBLE PRECISION,
                                       'Infinity'::DOUBLE PRECISION,
                                       '-Infinity'::DOUBLE PRECISION
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_numeric_maximum_finite CHECK (
        numeric_maximum IS NULL
            OR numeric_maximum NOT IN (
                                       'NaN'::DOUBLE PRECISION,
                                       'Infinity'::DOUBLE PRECISION,
                                       '-Infinity'::DOUBLE PRECISION
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_numeric_order CHECK (
        numeric_minimum IS NULL
            OR numeric_maximum IS NULL
            OR numeric_minimum <= numeric_maximum
        ),
    CONSTRAINT ck_hourly_sensor_summaries_temperature_range CHECK (
        unit IS DISTINCT FROM 'C'
            OR numeric_minimum IS NULL
            OR numeric_minimum >= -273.15
        ),
    CONSTRAINT ck_hourly_sensor_summaries_temperature_sum CHECK (
        unit IS DISTINCT FROM 'C'
            OR numeric_sum IS NULL
            OR numeric_sum >= -273.15::NUMERIC * source_sample_count
        ),
    CONSTRAINT ck_hourly_sensor_summaries_humidity_range CHECK (
        unit IS DISTINCT FROM 'PERCENT'
            OR (
            (numeric_minimum IS NULL OR numeric_minimum >= 0.0)
                AND
            (numeric_maximum IS NULL OR numeric_maximum <= 100.0)
            )
        ),
    CONSTRAINT ck_hourly_sensor_summaries_humidity_sum CHECK (
        unit IS DISTINCT FROM 'PERCENT'
            OR numeric_sum IS NULL
            OR numeric_sum BETWEEN 0::NUMERIC
            AND 100::NUMERIC * source_sample_count
        ),
    CONSTRAINT ck_hourly_sensor_summaries_refresh_order
        CHECK (finalized_at <= refreshed_at)
);

CREATE INDEX ix_hourly_sensor_summaries_sensor_bucket_end
    ON hourly_sensor_summaries (sensor_id, bucket_end, id);


CREATE TABLE daily_sensor_summaries
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id             BIGINT                                  NOT NULL,
    local_date            DATE                                    NOT NULL,
    time_zone_id          VARCHAR(64)                             NOT NULL,
    bucket_start          TIMESTAMPTZ                             NOT NULL,
    bucket_end            TIMESTAMPTZ                             NOT NULL,
    source_sample_count   BIGINT                                  NOT NULL,
    unit                  VARCHAR(20),
    numeric_sum           NUMERIC,
    numeric_minimum       DOUBLE PRECISION,
    numeric_maximum       DOUBLE PRECISION,
    true_sample_count     BIGINT,
    finalized_at          TIMESTAMPTZ                             NOT NULL,
    refreshed_at          TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_daily_sensor_summaries PRIMARY KEY (id),
    CONSTRAINT fk_daily_sensor_summaries_sensor
        FOREIGN KEY (sensor_id)
            REFERENCES sensors (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_daily_sensor_summaries_sensor_bucket_start
        UNIQUE (sensor_id, bucket_start),
    CONSTRAINT uk_daily_sensor_summaries_sensor_local_date_zone
        UNIQUE (sensor_id, local_date, time_zone_id),
    CONSTRAINT ck_daily_sensor_summaries_timezone_not_blank
        CHECK (btrim(time_zone_id) <> ''),
    CONSTRAINT ck_daily_sensor_summaries_bucket
        CHECK (bucket_start < bucket_end),
    CONSTRAINT ck_daily_sensor_summaries_sample_count
        CHECK (source_sample_count >= 0),
    CONSTRAINT ck_daily_sensor_summaries_unit CHECK (
        unit IS NULL
            OR unit IN ('C', 'PERCENT')
        ),
    CONSTRAINT ck_daily_sensor_summaries_value_shape CHECK (
        (
            unit IS NOT NULL
                AND true_sample_count IS NULL
                AND (
                (
                    source_sample_count = 0
                        AND numeric_sum IS NULL
                        AND numeric_minimum IS NULL
                        AND numeric_maximum IS NULL
                    )
                    OR
                (
                    source_sample_count > 0
                        AND numeric_sum IS NOT NULL
                        AND numeric_minimum IS NOT NULL
                        AND numeric_maximum IS NOT NULL
                    )
                )
            )
            OR
        (
            unit IS NULL
                AND numeric_sum IS NULL
                AND numeric_minimum IS NULL
                AND numeric_maximum IS NULL
                AND true_sample_count IS NOT NULL
            )
        ),
    CONSTRAINT ck_daily_sensor_summaries_true_sample_count CHECK (
        true_sample_count IS NULL
            OR true_sample_count BETWEEN 0 AND source_sample_count
        ),
    CONSTRAINT ck_daily_sensor_summaries_numeric_sum_finite CHECK (
        numeric_sum IS NULL
            OR numeric_sum NOT IN (
                                   'NaN'::NUMERIC,
                                   'Infinity'::NUMERIC,
                                   '-Infinity'::NUMERIC
            )
        ),
    CONSTRAINT ck_daily_sensor_summaries_numeric_minimum_finite CHECK (
        numeric_minimum IS NULL
            OR numeric_minimum NOT IN (
                                       'NaN'::DOUBLE PRECISION,
                                       'Infinity'::DOUBLE PRECISION,
                                       '-Infinity'::DOUBLE PRECISION
            )
        ),
    CONSTRAINT ck_daily_sensor_summaries_numeric_maximum_finite CHECK (
        numeric_maximum IS NULL
            OR numeric_maximum NOT IN (
                                       'NaN'::DOUBLE PRECISION,
                                       'Infinity'::DOUBLE PRECISION,
                                       '-Infinity'::DOUBLE PRECISION
            )
        ),
    CONSTRAINT ck_daily_sensor_summaries_numeric_order CHECK (
        numeric_minimum IS NULL
            OR numeric_maximum IS NULL
            OR numeric_minimum <= numeric_maximum
        ),
    CONSTRAINT ck_daily_sensor_summaries_temperature_range CHECK (
        unit IS DISTINCT FROM 'C'
            OR numeric_minimum IS NULL
            OR numeric_minimum >= -273.15
        ),
    CONSTRAINT ck_daily_sensor_summaries_temperature_sum CHECK (
        unit IS DISTINCT FROM 'C'
            OR numeric_sum IS NULL
            OR numeric_sum >= -273.15::NUMERIC * source_sample_count
        ),
    CONSTRAINT ck_daily_sensor_summaries_humidity_range CHECK (
        unit IS DISTINCT FROM 'PERCENT'
            OR (
            (numeric_minimum IS NULL OR numeric_minimum >= 0.0)
                AND
            (numeric_maximum IS NULL OR numeric_maximum <= 100.0)
            )
        ),
    CONSTRAINT ck_daily_sensor_summaries_humidity_sum CHECK (
        unit IS DISTINCT FROM 'PERCENT'
            OR numeric_sum IS NULL
            OR numeric_sum BETWEEN 0::NUMERIC
            AND 100::NUMERIC * source_sample_count
        ),
    CONSTRAINT ck_daily_sensor_summaries_refresh_order
        CHECK (finalized_at <= refreshed_at)
);

CREATE INDEX ix_daily_sensor_summaries_sensor_bucket_end
    ON daily_sensor_summaries (sensor_id, bucket_end, id);


CREATE TABLE sensor_rollup_checkpoints
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id                    BIGINT                                  NOT NULL,
    stage                        VARCHAR(30)                             NOT NULL,
    coverage_started_at          TIMESTAMPTZ                             NOT NULL,
    covered_until                TIMESTAMPTZ                             NOT NULL,
    last_attempted_bucket_start  TIMESTAMPTZ,
    last_attempted_at            TIMESTAMPTZ,
    last_successful_bucket_start TIMESTAMPTZ,
    last_successful_bucket_end   TIMESTAMPTZ,
    last_successful_at           TIMESTAMPTZ,
    last_advanced_at             TIMESTAMPTZ,
    created_at                   TIMESTAMPTZ                             NOT NULL,
    updated_at                   TIMESTAMPTZ                             NOT NULL,
    CONSTRAINT pk_sensor_rollup_checkpoints PRIMARY KEY (id),
    CONSTRAINT fk_sensor_rollup_checkpoints_sensor
        FOREIGN KEY (sensor_id)
            REFERENCES sensors (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_sensor_rollup_checkpoints_sensor_stage
        UNIQUE (sensor_id, stage),
    CONSTRAINT ck_sensor_rollup_checkpoints_stage CHECK (
        stage IN ('RAW_TO_HOURLY', 'HOURLY_TO_DAILY')
        ),
    CONSTRAINT ck_sensor_rollup_checkpoints_coverage CHECK (
        coverage_started_at <= covered_until
        ),
    CONSTRAINT ck_sensor_rollup_checkpoints_raw_hour_boundaries CHECK (
        stage <> 'RAW_TO_HOURLY'
            OR (
            coverage_started_at = (
                date_trunc(
                        'hour',
                        coverage_started_at AT TIME ZONE 'UTC'
                ) AT TIME ZONE 'UTC'
                )
                AND
            covered_until = (
                date_trunc(
                        'hour',
                        covered_until AT TIME ZONE 'UTC'
                ) AT TIME ZONE 'UTC'
                )
            )
        ),
    CONSTRAINT ck_sensor_rollup_checkpoints_attempt_shape CHECK (
        (
            last_attempted_bucket_start IS NULL
                AND last_attempted_at IS NULL
            )
            OR
        (
            last_attempted_bucket_start IS NOT NULL
                AND last_attempted_at IS NOT NULL
            )
        ),
    CONSTRAINT ck_sensor_rollup_checkpoints_success_shape CHECK (
        (
            last_successful_bucket_start IS NULL
                AND last_successful_bucket_end IS NULL
                AND last_successful_at IS NULL
            )
            OR
        (
            last_successful_bucket_start IS NOT NULL
                AND last_successful_bucket_end IS NOT NULL
                AND last_successful_at IS NOT NULL
                AND last_successful_bucket_start
                < last_successful_bucket_end
                AND last_successful_bucket_start
                >= coverage_started_at
                AND last_successful_bucket_end
                <= covered_until
            )
        ),
    CONSTRAINT ck_sensor_rollup_checkpoints_timestamp_order CHECK (
        created_at <= updated_at
            AND (
            last_attempted_at IS NULL
                OR last_attempted_at BETWEEN created_at AND updated_at
            )
            AND (
            last_successful_at IS NULL
                OR last_successful_at BETWEEN created_at AND updated_at
            )
            AND (
            last_advanced_at IS NULL
                OR last_advanced_at BETWEEN created_at AND updated_at
            )
        )
);

CREATE INDEX ix_sensor_rollup_checkpoints_stage_covered_until
    ON sensor_rollup_checkpoints (stage, covered_until, sensor_id);