CREATE TABLE alert_rules
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id            BIGINT                                  NOT NULL,
    sensor_id           BIGINT                                  NOT NULL,

    rule_type           VARCHAR(40)                             NOT NULL,

    comparison_operator VARCHAR(30),
    threshold_value     DOUBLE PRECISION,
    threshold_unit      VARCHAR(25),

    event_type          VARCHAR(40),

    enabled             BOOLEAN                                 NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ                             NOT NULL,
    updated_at          TIMESTAMPTZ                             NOT NULL,

    CONSTRAINT pk_alert_rules PRIMARY KEY (id),
    CONSTRAINT fk_alert_rules_owner FOREIGN KEY (owner_id) REFERENCES app_users (id),
    CONSTRAINT fk_alert_rules_sensor FOREIGN KEY (sensor_id) REFERENCES sensors (id),

    CONSTRAINT ck_alert_rules_type CHECK (
        rule_type IN ('NUMERIC_THRESHOLD', 'EVENT_DETECTED')
        ),

    CONSTRAINT ck_alert_rules_comparison_operator CHECK (
        comparison_operator IS NULL OR comparison_operator IN ('ABOVE', 'BELOW')
        ),

    CONSTRAINT ck_alert_rules_event_type CHECK (
        event_type IS NULL OR event_type IN ('MOTION_DETECTED')
        ),

    CONSTRAINT ck_alert_rules_shape CHECK (
        (
            rule_type = 'NUMERIC_THRESHOLD'
                AND comparison_operator IS NOT NULL
                AND threshold_value IS NOT NULL
                AND threshold_unit IS NOT NULL
                AND btrim(threshold_unit) <> ''
                AND event_type IS NULL
            )
            OR
        (
            rule_type = 'EVENT_DETECTED'
                AND event_type IS NOT NULL
                AND comparison_operator IS NULL
                AND threshold_value IS NULL
                AND threshold_unit IS NULL
            )
        )
);

CREATE INDEX ix_alert_rules_owner_id ON alert_rules (owner_id);
CREATE INDEX ix_alert_rules_sensor_enabled ON alert_rules (sensor_id, enabled);


-- Cleanup: Dropping the legacy/deprecated sensor_data table.
-- This was replaced by sensor_readings in V4__ but the drop was deferred.
DROP TABLE sensor_data;